Repository operator-framework/helm-app-operator-kit, pull requests merged in 2018-11, with the labels that each got.

#65 pkg/helm: initial package refactoring for integration into operator-sdk
  helm-app-operator/cmd/manager/main.go
  helm-app-operator/pkg/apis/app/v1alpha1/zz_generated.deepcopy.go
  helm-app-operator/pkg/helm/client/client.go
  helm-app-operator/pkg/helm/client/doc.go
  helm-app-operator/pkg/helm/controller/controller.go
  helm-app-operator/pkg/helm/controller/doc.go
  helm-app-operator/pkg/helm/controller/reconcile.go
  helm-app-operator/pkg/helm/engine/doc.go
  helm-app-operator/pkg/helm/engine/ownerref.go
  helm-app-operator/pkg/helm/engine/ownerref_test.go
  helm-app-operator/pkg/helm/internal/types/doc.go
  helm-app-operator/pkg/helm/internal/types/types.go
  helm-app-operator/pkg/helm/internal/types/types_test.go
  helm-app-operator/pkg/helm/internal/util/diff.go
  helm-app-operator/pkg/helm/internal/util/doc.go
  helm-app-operator/pkg/helm/internal/util/resource.go
  helm-app-operator/pkg/helm/release/doc.go
  helm-app-operator/pkg/helm/release/helm.go
  helm-app-operator/pkg/helm/release/helm_test.go
Labels: size/L

#64 README.md: documenting build, config, and new features; refactoring
  README.md
  examples/tomcat-operator/rbac.yaml
  helm-app-operator/README.md
  helm-app-operator/test/memcached-operator/deploy/rbac.yaml
Labels: size/L

#68 pkg/helm: rename installer to manager
  helm-app-operator/cmd/manager/main.go
  helm-app-operator/pkg/helm/controller/controller.go
  helm-app-operator/pkg/helm/controller/reconcile.go
  helm-app-operator/pkg/helm/release/doc.go
  helm-app-operator/pkg/helm/release/helm_test.go
  helm-app-operator/pkg/helm/release/manager.go
  helm-app-operator/pkg/helm/release/new.go
Labels: size/L

#69 main.go,pkg/helm; refactoring manager to manager and manager factory
  helm-app-operator/cmd/manager/main.go
  helm-app-operator/pkg/helm/controller/controller.go
  helm-app-operator/pkg/helm/controller/reconcile.go
  helm-app-operator/pkg/helm/release/manager.go
  helm-app-operator/pkg/helm/release/new.go
Labels: size/L

#71 Gopkg.toml: constrain helm to 2.11.0, remove redundant prune option
  helm-app-operator/Gopkg.toml
Labels: size/XS

#72 Reorganize manager
  helm-app-operator/pkg/helm/release/manager.go
  helm-app-operator/pkg/helm/release/manager_factory.go
Labels: size/L

#74 cmd/manager;pkg/helm: migrating to logr-based logging
  helm-app-operator/Gopkg.lock
  helm-app-operator/cmd/manager/main.go
  helm-app-operator/hack/tests/e2e-helm.sh
  helm-app-operator/pkg/helm/controller/controller.go
  helm-app-operator/pkg/helm/controller/reconcile.go
  helm-app-operator/pkg/helm/engine/ownerref.go
  helm-app-operator/pkg/helm/release/manager.go
Labels: size/L

#75 Link to install guide of operator lifecycle manager
  examples/tomcat-operator/README.md
Labels: needs-ok-to-test, size/XS
