Repository operator-framework/helm-app-operator-kit, pull requests merged in 2018-10, with the labels that each got.

#46 helm-app-operator: transitioning to use controller-runtime
  Dockerfile
  ci.Dockerfile
  helm-app-operator/Gopkg.lock
  helm-app-operator/build/Dockerfile
  helm-app-operator/build/build.sh
  helm-app-operator/cmd/helm-app-operator/main.go
  helm-app-operator/cmd/manager/main.go
  helm-app-operator/pkg/apis/app/v1alpha1/register.go
  helm-app-operator/pkg/apis/app/v1alpha1/types.go
  helm-app-operator/pkg/apis/app/v1alpha1/types_test.go
  helm-app-operator/pkg/helm/client.go
  helm-app-operator/pkg/helm/controller/controller.go
  helm-app-operator/pkg/helm/controller/reconcile.go
  helm-app-operator/pkg/helm/helm.go
  helm-app-operator/pkg/stub/handler.go
  helm-app-operator/scripts/codegen/boilerplate.go.txt
  helm-app-operator/tmp/build/docker_build.sh
  helm-app-operator/tmp/codegen/boilerplate.go.txt
  helm-app-operator/tmp/codegen/update-generated.sh
Labels: size/XL

#47 pkg/helm,pkg/helm/controller: fixing reconciliation loop bugs
  helm-app-operator/pkg/helm/controller/reconcile.go
  helm-app-operator/pkg/helm/helm.go
Labels: size/S

#48 Support multiple resources
  helm-app-operator/Gopkg.lock
  helm-app-operator/cmd/manager/main.go
  helm-app-operator/pkg/helm/controller/controller.go
  helm-app-operator/pkg/helm/controller/reconcile.go
  helm-app-operator/pkg/helm/helm.go
Labels: size/L

#51 Reconcile resources
  helm-app-operator/Gopkg.lock
  helm-app-operator/pkg/helm/controller/controller.go
  helm-app-operator/pkg/helm/controller/reconcile.go
  helm-app-operator/pkg/helm/engine.go
  helm-app-operator/pkg/helm/helm.go
Labels: size/L

#53 hack,test: initial e2e test for helm operator
  .travis.yml
  helm-app-operator/Gopkg.lock
  helm-app-operator/Makefile
  helm-app-operator/cmd/manager/main.go
  helm-app-operator/hack/check_error_case.sh
  helm-app-operator/hack/check_license.sh
  helm-app-operator/hack/ci/setup-openshift.sh
  helm-app-operator/hack/lib/test_lib.sh
  helm-app-operator/hack/tests/e2e-helm.sh
  helm-app-operator/hack/tests/sanity-check.sh
  helm-app-operator/hack/tests/unit.sh
  helm-app-operator/pkg/apis/app/v1alpha1/doc.go
  helm-app-operator/pkg/apis/app/v1alpha1/types.go
  helm-app-operator/pkg/apis/app/v1alpha1/types_test.go
  helm-app-operator/pkg/helm/client.go
  helm-app-operator/pkg/helm/controller/controller.go
  helm-app-operator/pkg/helm/controller/reconcile.go
  helm-app-operator/pkg/helm/engine.go
  helm-app-operator/pkg/helm/engine_test.go
  helm-app-operator/pkg/helm/helm.go
  helm-app-operator/pkg/helm/helm_test.go
  helm-app-operator/test/memcached-operator/Dockerfile
  helm-app-operator/test/memcached-operator/deploy/cr.yaml
  helm-app-operator/test/memcached-operator/deploy/crd.yaml
  helm-app-operator/test/memcached-operator/deploy/operator.yaml.tmpl
  helm-app-operator/test/memcached-operator/deploy/rbac.yaml
  helm-app-operator/test/memcached-operator/watches.yaml
  helm-app-operator/version/version.go
Labels: size/XL

#38 Fix for #36 : Adding Ownerref for Multi Document yaml file
  helm-app-operator/Gopkg.lock
  helm-app-operator/pkg/helm/engine.go
  helm-app-operator/pkg/helm/engine_test.go
Labels: size/L

#57 Improve release name uniqueness and ownership
  helm-app-operator/Gopkg.lock
  helm-app-operator/pkg/helm/helm.go
Labels: size/M

#61 pkg/helm: adding manifest diff logging
  helm-app-operator/Gopkg.lock
  helm-app-operator/pkg/helm/helm.go
Labels: size/M
